Reverse commenting out git status --porcelain
It was wrongly commented out in this commit:
7c9d4f134222692450d13efcabb0c1e16d6c1b2f

diff --git a/script/release/update_locales b/script/release/update_locales
--- a/script/release/update_locales
+++ b/script/release/update_locales
@@ -6,10 +6,10 @@
 # Exit on error or uncommitted changes
 # TODO: check that master matches upstream/master
 set -e
-#if [ ! -z "$(git status --porcelain)" ]; then
-#  echo "Aborted: git working directory is not clean."
-#  exit 1
-#fi
+if [ ! -z "$(git status --porcelain)" ]; then
+  echo "Aborted: git working directory is not clean."
+  exit 1
+fi
 
 echo "\n*** Checking out latest master... ***\n"
 git checkout master
